# Generated by Django 3.2.4 on 2021-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
            ],
            options={
                'db_table': 'information',
            },
        ),
    ]
