# Generated by Django 3.1.2 on 2021-07-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='ユーザーID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
